version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install pytest

  build:
    commands:
      - pytest test_lambda.py

artifacts:
  files:
    - lambda_function.py