version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install pytest
  build:
    commands:
      - pytest test_lambda.py
      - mkdir -p package
      - cp lambda_function.py package/
      - cd package && zip -r ../lambda.zip .
artifacts:
  files:
    - lambda.zip